name: Publish

env:
  config: Release
  refactSolution: RefactExtension.sln
  vsixContainer: ${{ github.workspace }}\RefactExtension.vsix
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  workflow_dispatch:

jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
            arch: x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
            arch: arm64

    env:
      LLM_LS_TARGET: ${{ matrix.target }}
    
    name: Publish in marketplace (VSCE) (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Install VSCE
        run: |
          npm install -g @vscode/vsce
          
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          repo: smallcloudai/refact-lsp
          branch: ${{ inputs.branch }} 
          path: ./assets
          name: dist-${{ matrix.target }}

      - name: Nerdbank.GitVersioning
        uses: aarnott/nbgv@v0.3
        id: nbgv

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{ matrix.arch }}
      
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - run: nuget restore ${{ env.refactSolution }}

      - name: MSBuild ${{ env.refactSolution }}
        run: |
          msbuild ${{ env.refactSolution }} /p:Configuration=${{ env.config }} /p:TargetVsixContainer=${{ env.vsixContainer }} /p:DeployExtension=False /verbosity:minimal
     
      - name: Publish VSCE extension
        shell: bash
        run: |
          vsce publish --pat ${{secrets.VSCE_PAT}} --packagePath ${{ env.vsixContainer }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ${{ env.vsixContainer }}